local HAPPINESS_RATE = 1
local HUNGER_RATE = 1
local HEALTH_RATE = 0.5

local PLAY_DURATION = 5
local SLEEP_DURATION = 5

local DIRTY_INTERVAL = 8

return {
    HAPPINESS_RATE = HAPPINESS_RATE,
    HUNGER_RATE = HUNGER_RATE,
    HEALTH_RATE = HEALTH_RATE,
    PLAY_DURATION = PLAY_DURATION,
    SLEEP_DURATION = SLEEP_DURATION,
    DIRTY_INTERVAL = DIRTY_INTERVAL
}
